name: Build & Upload APK to Localhost PHP

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout kode sumber
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build APK
        run: ./gradlew assembleRelease

      - name: Upload APK ke Server PHP Localhost
        run: |
          curl -X POST "http://localhost:8080/upload.php" \
               -H "Content-Type: multipart/form-data" \
               -F "apk=@app/build/outputs/apk/release/app-release.apk"
